import {copy,validRect,ppmOf,canonicalScheme,reproject,resizeFromHandle} from './geometry.mjs?v=placement-editor';
import {fileURL} from './persistence.mjs';
export const svgNode=(tag,attrs={})=>{const node=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))node.setAttribute(k,v);return node;};
const schemeHandles=r=>[['nw',r.x,r.y],['n',r.x+r.w/2,r.y],['ne',r.x+r.w,r.y],['e',r.x+r.w,r.y+r.h/2],['se',r.x+r.w,r.y+r.h],['s',r.x+r.w/2,r.y+r.h],['sw',r.x,r.y+r.h],['w',r.x,r.y+r.h/2]];
const handleCursor={nw:'nwse-resize',se:'nwse-resize',ne:'nesw-resize',sw:'nesw-resize',n:'ns-resize',s:'ns-resize',e:'ew-resize',w:'ew-resize'};
const colorValue={black:0,white:1,gray:.25};
export class Editor {
 constructor(svg,{getState,onSelect,onChange,onDraw,onZoom}){Object.assign(this,{svg,getState,onSelect,onChange,onDraw,onZoom,scale:1,tx:50,ty:40,tool:'select',clean:false,imageSize:{w:800,h:900},space:false,gesture:null,imagePath:''});svg.addEventListener('pointerdown',e=>this.down(e));svg.addEventListener('pointermove',e=>this.move(e));svg.addEventListener('pointerup',e=>this.up(e));svg.addEventListener('pointercancel',()=>this.cancel());svg.addEventListener('wheel',e=>{e.preventDefault();this.zoom(Math.exp(-e.deltaY*.001),e.offsetX,e.offsetY);},{passive:false});svg.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('keydown',e=>{if(e.code==='Space'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();this.space=true;svg.style.cursor='grab';}});window.addEventListener('keyup',e=>{if(e.code==='Space'){this.space=false;svg.style.cursor='';}});window.addEventListener('blur',()=>{this.space=false;this.cancel();});new ResizeObserver(()=>this.render()).observe(svg);}
 point(e){const b=this.svg.getBoundingClientRect();return {x:(e.clientX-b.left-this.tx)/this.scale,y:(e.clientY-b.top-this.ty)/this.scale};}
 fit(){const b=this.svg.getBoundingClientRect();this.scale=Math.min((b.width-100)/this.imageSize.w,(b.height-80)/this.imageSize.h);this.scale=Math.max(.03,this.scale);this.tx=(b.width-this.imageSize.w*this.scale)/2;this.ty=(b.height-this.imageSize.h*this.scale)/2;this.render();}
 zoom(factor,x=this.svg.clientWidth/2,y=this.svg.clientHeight/2){const next=Math.min(12,Math.max(.025,this.scale*factor));this.tx=x-(x-this.tx)*next/this.scale;this.ty=y-(y-this.ty)*next/this.scale;this.scale=next;this.render();}
 loadImage(p){const path=p?.inputs?.bag_image?fileURL(p,p.inputs.bag_image):'';if(path===this.imagePath)return;this.imagePath=path;if(path){const image=new Image();image.onload=()=>{if(this.imagePath!==path)return;this.imageSize={w:image.naturalWidth,h:image.naturalHeight};this.fit();this.onImageLoad?.();};image.onerror=()=>this.onChange(null,false,new Error('产品图片加载失败，请重新导入。'));image.src=path;}}
 render(){const {project:p,selection,schemeId}=this.getState();this.svg.replaceChildren();this.onZoom?.(this.scale);if(!p)return;this.loadImage(p);const g=svgNode('g',{transform:`translate(${this.tx} ${this.ty}) scale(${this.scale})`});this.svg.append(g);if(p.inputs?.bag_image)g.append(svgNode('image',{href:fileURL(p,p.inputs.bag_image),x:0,y:0,width:this.imageSize.w,height:this.imageSize.h}));const scheme=p.schemes?.find(s=>s.id===schemeId);if(scheme&&validRect(scheme.logo_px)&&p.inputs?.logo_preview){const r=scheme.logo_px,mode=['original','black','white','gray'].includes(scheme.color)?scheme.color:'original',image=svgNode('image',{href:fileURL(p,p.inputs.logo_preview),x:r.x,y:r.y,width:r.w,height:r.h,preserveAspectRatio:'none','data-kind':'scheme','data-id':scheme.id});if(mode!=='original'){const value=colorValue[mode],id=`logo-color-${scheme.id}`,defs=svgNode('defs'),filter=svgNode('filter',{id});filter.append(svgNode('feColorMatrix',{type:'matrix',values:`0 0 0 0 ${value} 0 0 0 0 ${value} 0 0 0 0 ${value} 0 0 0 1 0`}));defs.append(filter);g.append(defs);image.setAttribute('filter',`url(#${id})`);}g.append(image);}
 if(!this.clean){if(validRect(p.calibration?.product_frame))this.rect(g,p.calibration.product_frame,'product','product','#a69869',selection);for(const f of p.frames||[])this.rect(g,f,'frame',f.id,'#769b7c',selection);if(validRect(p.crop))this.rect(g,p.crop,'crop','crop','#9397b8',selection);if(scheme&&validRect(scheme.logo_px))this.rect(g,scheme.logo_px,'scheme',scheme.id,'#2b7755',selection);if(this.gesture?.drawRect)this.rect(g,this.gesture.drawRect,'drawing','drawing','#447359',null);}
 }
 rect(g,r,kind,id,color,selection){const selected=selection?.kind===kind&&selection.id===id;const outline=svgNode('rect',{x:r.x,y:r.y,width:r.w,height:r.h,fill:kind==='scheme'?'transparent':`${color}09`,stroke:color,'stroke-width':selected?1.5:1,'vector-effect':'non-scaling-stroke','stroke-dasharray':selected?'none':kind==='crop'?'5 4':'4 3','data-kind':kind,'data-id':id});outline.style.cursor=kind==='drawing'?'crosshair':'move';g.append(outline);if(kind!=='scheme'){const text=svgNode('text',{x:r.x+5/this.scale,y:r.y-7/this.scale,fill:color,'font-size':10/this.scale,'pointer-events':'none'});text.textContent=kind==='product'?'产品尺寸':kind==='crop'?'裁剪范围':this.getState().project.frames.find(f=>f.id===id)?.name||'印标区域';g.append(text);}const handles=kind==='scheme'?schemeHandles(r):[['nw',r.x,r.y],['ne',r.x+r.w,r.y],['sw',r.x,r.y+r.h],['se',r.x+r.w,r.y+r.h]];if(selected)for(const [handle,x,y] of handles){const sz=8/this.scale;const n=svgNode('rect',{x:x-sz/2,y:y-sz/2,width:sz,height:sz,fill:'#fff',stroke:color,'stroke-width':1,'vector-effect':'non-scaling-stroke','data-kind':kind,'data-id':id,'data-handle':handle});n.style.cursor=handleCursor[handle];g.append(n);}}
 getRect(p,selection){return selection.kind==='product'?p.calibration?.product_frame:selection.kind==='crop'?p.crop:selection.kind==='frame'?p.frames.find(f=>f.id===selection.id):p.schemes.find(s=>s.id===selection.id)?.logo_px;}
 down(e){const state=this.getState();if(state.busy||!state.project)return;if(e.button!==0&&e.button!==1)return;this.svg.setPointerCapture(e.pointerId);const start=this.point(e);if(this.space||e.button===1){this.gesture={pan:true,client:{x:e.clientX,y:e.clientY},tx:this.tx,ty:this.ty};return;}if(this.clean)return;if(this.tool!=='select'){this.gesture={draw:true,start,before:copy(state.project)};return;}const kind=e.target.getAttribute('data-kind'),id=e.target.getAttribute('data-id');if(!kind){this.onSelect(null);return;}const selection={kind,id};this.onSelect(selection);const r=this.getRect(state.project,selection);if(!validRect(r))return;this.gesture={start,selection,handle:e.target.getAttribute('data-handle'),rect:copy(r),before:copy(state.project),changed:false};}
 move(e){const g=this.gesture;if(!g)return;if(g.pan){this.tx=g.tx+e.clientX-g.client.x;this.ty=g.ty+e.clientY-g.client.y;this.render();return;}const q=this.point(e),dx=q.x-g.start.x,dy=q.y-g.start.y;if(g.draw){g.drawRect={x:Math.min(q.x,g.start.x),y:Math.min(q.y,g.start.y),w:Math.abs(dx),h:Math.abs(dy)};this.render();return;}let r={...g.rect};if(g.handle){if(g.selection.kind==='scheme'){const scheme=g.before.schemes.find(item=>item.id===g.selection.id),aspect=g.before.asset?.width/g.before.asset?.height||g.rect.w/g.rect.h;r=resizeFromHandle(g.rect,g.handle,{x:dx,y:dy},aspect,scheme?.lock_aspect!==false);}else{const west=g.handle.includes('w'),north=g.handle.includes('n');r.w=Math.max(1,g.rect.w+(west?-dx:dx));r.h=Math.max(1,g.rect.h+(north?-dy:dy));if(west)r.x=g.rect.x+g.rect.w-r.w;if(north)r.y=g.rect.y+g.rect.h-r.h;}}else{r.x+=dx;r.y+=dy;}let p=copy(g.before);const selection=g.selection;if(selection.kind==='product'){p.calibration={...p.calibration,product_frame:r};p=reproject(p);}else if(selection.kind==='frame'){Object.assign(p.frames.find(f=>f.id===selection.id),r);p=reproject(p);}else if(selection.kind==='crop')p.crop=r;else{const s=p.schemes.find(s=>s.id===selection.id);s.logo_px=r;const frame=p.frames.find(f=>f.id===s.frame_id),ppm=ppmOf(p);if(ppm&&frame)Object.assign(s,canonicalScheme(s,frame,ppm));}g.changed=true;this.onChange(p,false);}
 up(){const g=this.gesture;if(!g)return;this.gesture=null;if(g.draw&&g.drawRect?.w*this.scale>6&&g.drawRect?.h*this.scale>6)this.onDraw(this.tool,g.drawRect);else if(g.changed)this.onChange(this.getState().project,true);this.render();}
 cancel(){const g=this.gesture;this.gesture=null;if(g?.before&&!g.draw)this.onChange(g.before,false);this.render();}
 thumbnail(p,scheme){const svg=svgNode('svg',{viewBox:`0 0 ${this.imageSize.w} ${this.imageSize.h}`});if(p.inputs?.bag_image)svg.append(svgNode('image',{href:fileURL(p,p.inputs.bag_image),width:this.imageSize.w,height:this.imageSize.h}));if(validRect(scheme.logo_px)&&p.inputs?.logo_preview){const r=scheme.logo_px;svg.append(svgNode('image',{href:fileURL(p,p.inputs.logo_preview),x:r.x,y:r.y,width:r.w,height:r.h}));}return svg;}
}
