import {copy,positive,validRect,ppmOf,newScheme,projectRect,reproject,exportReady,History} from './geometry.mjs?v=placement-editor';
import {SaveQueue,api,projectURL,fileURL,runExclusive} from './persistence.mjs';
import {Editor} from './editor.mjs?v=placement-editor';
import {$,el,button,field,section,dialog,dialogError,closeDialog,errorBanner} from './ui.mjs';
import {logoPickerDialog} from './assets.mjs?v=candidate-picker';
import {activeScheme,canCustomerExport,nextPrimaryAction} from './state.mjs';

const state={project:null,projects:[],selection:null,schemeId:null,busy:false,history:null,queue:null,dirty:false,exported:null,health:null,leftTab:'assets'};
const editor=new Editor($('editor'),{getState:()=>state,onSelect:selection=>{state.selection=selection;if(selection?.kind==='scheme')state.schemeId=selection.id;render();},onChange:(p,commit,error)=>{if(error){showError(error);return;}state.project=p;if(commit)changed();else{state.exported=null;editor.render();renderProperties();}},onDraw:(kind,r)=>{edit(p=>{if(kind==='product'){p.calibration={...p.calibration,product_frame:r};state.selection={kind:'product',id:'product'};}else if(kind==='crop'){p.crop=r;state.selection={kind:'crop',id:'crop'};}else{const f={...r,id:crypto.randomUUID(),name:`印标区域 ${p.frames.length+1}`};p.frames.push(f);const scheme=ensurePlacement(p,f);state.selection=scheme?{kind:'scheme',id:scheme.id}:{kind:'frame',id:f.id};}});setTool('select');},onZoom:scale=>$('zoom-label').textContent=`${Math.round(scale*100)}%`});
editor.onImageLoad=render;
function showError(error){errorBanner(error);$('retry-button').hidden=!state.queue?.error||error.code==='REVISION_CONFLICT';$('reopen-button').hidden=error.code!=='REVISION_CONFLICT';if(state.queue?.error)$('save-state').textContent=error.code==='REVISION_CONFLICT'?'版本冲突 · 已暂停保存':'保存失败 · 修改尚未写入';}
async function run(label,work){try{return await runExclusive(state,work,busy=>{if(busy)$('busy-label').textContent=label;$('busy-overlay').hidden=!busy;render();});}catch(error){showError(error);throw error;}}
function safe(work){return (...args)=>Promise.resolve().then(()=>work(...args)).catch(showError);}
async function refresh(){state.projects=await api('/api/projects');renderProjects();}
function adopt(p){state.project=copy(p);state.project.frames??=[];state.project.schemes??=[];state.project.inputs??={};state.history=new History(p);state.schemeId=activeScheme(p)?.id||p.schemes?.[0]?.id||null;state.selection=state.schemeId?{kind:'scheme',id:state.schemeId}:validRect(p.calibration?.product_frame)?{kind:'product',id:'product'}:null;state.dirty=false;state.exported=null;state.queue=new SaveQueue(data=>api(projectURL(data.name),{method:'PUT',body:data}),saved=>{state.project.revision=saved.revision;state.project.updated_at=saved.updated_at;state.project.schema_version=saved.schema_version;state.dirty=Boolean(state.queue.pending);$('save-state').textContent=state.dirty?'正在保存…':`已保存 · 修订 ${saved.revision}`;},showError);$('error-banner').hidden=true;render();if(state.project.schemes.length>1)legacySchemeDialog();}
async function openProject(name){await run('正在打开项目…',async()=>{await state.queue?.flush();adopt(await api(projectURL(name)));});}
function changed(){state.project=reproject(state.project);state.project.schema_version=3;state.history.commit(state.project);state.exported=null;state.dirty=true;state.queue.schedule(state.project);$('save-state').textContent='等待保存…';render();}
function edit(mutator){if(state.busy||!state.project)return;mutator(state.project);changed();}
async function mutation(path,body){await state.queue?.flush();const project=await api(projectURL(state.project.name)+path,{method:'POST',body});adopt(project);await refresh();return project;}
function nameDialog(clone=false){if(clone&&!state.project)return;const root=dialog(clone?'复制为新项目':'新建项目'),name=field('项目名称',clone?`${state.project.name} 副本`:'',()=>{},{type:'text'});root.append(name,el('p','muted','每个项目独立保存产品、素材、尺寸与排版方案。'));const footer=el('div','dialog-footer'),submit=button(clone?'创建副本':'创建项目',async()=>{const value=name.querySelector('input').value.trim();if(!value){dialogError(root,new Error('请输入项目名称'));return;}submit.disabled=true;try{await run('正在创建项目…',async()=>{await state.queue?.flush();const p=await api(clone?projectURL(state.project.name)+'/clone':'/api/projects',{method:'POST',body:{name:value}});adopt(p);await refresh();closeDialog();});}catch(error){dialogError(root,error);}finally{submit.disabled=false;}},'primary');footer.append(button('取消',closeDialog),submit);root.append(footer);name.querySelector('input').focus();name.querySelector('input').onkeydown=e=>{if(e.key==='Enter')submit.click();};}
function legacySchemeDialog(){const project=state.project;if(!project||project.schemes.length<2)return;let selected=project.schemes[0].id;const root=dialog('选择一个 Logo 继续编辑',{canClose:()=>false});root.append(el('p','muted','此任务来自旧版本，包含多个 Logo 放置。请选择一个保留为当前草稿。'));for(const [index,scheme]of project.schemes.entries()){const row=el('label','object-row'),radio=el('input');radio.type='radio';radio.name='legacy-scheme';radio.value=scheme.id;radio.checked=scheme.id===selected;radio.onchange=()=>{selected=scheme.id;};row.append(radio,el('span','',`Logo ${index+1}`));root.append(row);}const footer=el('div','dialog-footer');footer.append(button('继续编辑',()=>{const scheme=copy(state.project.schemes.find(item=>item.id===selected));edit(project=>{project.schemes=[scheme];state.schemeId=scheme.id;state.selection={kind:'scheme',id:scheme.id};});closeDialog();},'primary'));root.append(footer);}
const statusLabel={editing:'编辑中',waiting_feedback:'等待反馈',completed:'已完成'};
function formatUpdatedAt(value){if(!value)return '刚刚创建';const date=new Date(value);return Number.isNaN(date.getTime())?'刚刚更新':date.toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});}
function renderProjects(){const list=$('project-list');list.replaceChildren();const query=$('project-search').value.toLowerCase();for(const p of state.projects.filter(p=>p.name.toLowerCase().includes(query))){const b=button('',safe(()=>openProject(p.name)),`project-row${p.name===state.project?.name?' active':''}`),thumb=el('span',p.preview_path?'project-thumb':'project-icon'),desc=el('span','project-copy');if(p.preview_path){const img=el('img');img.src=fileURL(p,p.preview_path);img.alt='客户确认图缩略图';thumb.append(img);}else thumb.textContent='▱';desc.append(el('span','project-name',p.name),el('div','project-meta',`${formatUpdatedAt(p.updated_at)} · ${p.version_count||0} 个版本 · ${statusLabel[p.status]||'编辑中'}`));b.append(thumb,desc);list.append(b);}if(!list.childElementCount)list.append(el('p','empty-note',query?'没有匹配的任务':'还没有任务。点击“新建”，开始制作。'));}
function upload(kind){if(!state.project){nameDialog();return;}const input=el('input');input.type='file';input.accept=kind==='bag'?'.png,.jpg,.jpeg,.webp':'.svg,.pdf,.ai,.png,.jpg,.jpeg,.webp';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;if(kind==='bag'&&state.project.inputs.bag_image&&!confirm('替换产品图片会清空尺寸校准、参考框、裁剪和排版方案。是否继续？'))return;try{await run('正在导入素材…',async()=>{const data=new FormData();data.append('file',file);await mutation(`/upload/${kind}`,data);});}catch{}};input.click();}
async function analyze(){await run('正在分析与清理 Logo…',()=>mutation('/convert',{}));reviewAsset();}
function reviewAsset(){logoPickerDialog(state.project,ids=>run('正在应用 Logo…',()=>mutation('/asset/select',{candidate_ids:ids})));}
function renderAssets(){const root=$('assets-panel');root.replaceChildren();const p=state.project;if(!p){root.append(el('p','empty-note','选择任务后，可导入产品图和 Logo。'));return;}const status=el('label','field task-status','任务状态'),select=el('select');for(const [value,label]of Object.entries(statusLabel)){const option=el('option','',label);option.value=value;option.selected=(p.status||'editing')===value;select.append(option);}select.onchange=()=>edit(project=>{project.status=select.value;});status.append(select);root.append(status);for(const [kind,title,path,help]of [['bag','产品图',p.inputs.bag_image,'JPG / PNG / WebP'],['logo','Logo',p.inputs.logo_preview||p.asset?.source_preview,'SVG / PDF / AI / 位图']]){const card=el('div','asset-card'),thumb=el('div','asset-thumb');if(path){const img=el('img');img.src=fileURL(p,path);img.alt=title;thumb.append(img);}else thumb.append(el('span','muted',kind==='bag'?'＋ 添加产品图':'◇ 导入 Logo'));card.append(thumb,el('h3','',title),el('div','muted',kind==='logo'&&p.inputs.logo_source?p.inputs.logo_source.split('/').pop():help));const actions=el('div','asset-actions');actions.append(button(path?'替换文件':'导入文件',()=>upload(kind)));if(kind==='logo'&&(p.inputs.logo_source||p.inputs.logo_svg))actions.append(button(p.asset?'重新分析':'分析 Logo',safe(analyze)));if(kind==='logo'&&p.asset)actions.append(button('选择内容',reviewAsset));card.append(actions);root.append(card);}if(!p.asset&&(p.inputs.logo_source||p.inputs.logo_svg))root.append(el('div','notice','Logo 尚未完成分析。'));if(p.asset?.warnings?.length)root.append(el('div','notice',p.asset.warnings.map(w=>w.message||w).join('；')));}
function selectedFrame(){const p=state.project;if(!p)return null;if(state.selection?.kind==='frame')return p.frames.find(f=>f.id===state.selection.id);const s=p.schemes.find(s=>s.id===state.schemeId);return p.frames.find(f=>f.id===s?.frame_id)||p.frames[0];}
function ensurePlacement(project,frame=project.frames?.[0]){if(project.schemes?.length||!project.asset||!frame||!ppmOf(project))return null;const scheme=newScheme(project,frame.id);if(!scheme)return null;project.schemes=[scheme];state.schemeId=scheme.id;return scheme;}
function addScheme(){const p=state.project,f=selectedFrame();if(!f)return;if(p.schemes.length){state.schemeId=p.schemes[0].id;state.selection={kind:'scheme',id:state.schemeId};render();return;}edit(project=>{const scheme=ensurePlacement(project,f);if(scheme)state.selection={kind:'scheme',id:scheme.id};});}
const fmt=n=>Number.isFinite(n)?Number(n.toFixed(2)):'';
function fieldsRow(...fields){const row=el('div','field-row');row.append(...fields);return row;}
function renderProperties(){const root=$('properties'),p=state.project;root.replaceChildren();$('selection-kind').textContent=({product:'产品框',frame:'印标区域',scheme:'Logo',crop:'裁剪框'})[state.selection?.kind]||'项目';if(!p){root.append(el('p','empty-note','从左侧打开或新建任务。所有修改自动保存在本机。'));return;}const calibration=section('产品校准');calibration.append(field('产品实际宽度 / mm',p.calibration?.width_mm||'',v=>{if(!positive(v)){showError(new Error('产品宽度必须大于 0'));return;}edit(p=>{p.calibration={...p.calibration,width_mm:v};const scheme=ensurePlacement(p);if(scheme)state.selection={kind:'scheme',id:scheme.id};});},{min:.01}));const ppm=ppmOf(p);calibration.append(el('p','muted',ppm?`比例 ${fmt(ppm)} px/mm · 高度 ${fmt(p.calibration.product_frame.h/ppm)} mm`:'请在图片上绘制产品尺寸框，再输入真实宽度。'));if(!validRect(p.calibration?.product_frame))calibration.append(button('绘制产品尺寸框',()=>setTool('product'),'full'));root.append(calibration);const selection=state.selection;
 if(selection?.kind==='scheme'){const s=p.schemes.find(s=>s.id===selection.id);if(!s)return;const group=section('Logo 尺寸与定位');const frameField=el('label','field','印标区域'),select=el('select');for(const f of p.frames){const opt=el('option','',f.name||'印标区域');opt.value=f.id;opt.selected=f.id===s.frame_id;select.append(opt);}select.onchange=()=>edit(p=>{p.schemes.find(x=>x.id===s.id).frame_id=select.value;});frameField.append(select);group.append(frameField);const aspect=p.asset?.width/p.asset?.height||s.size_mm?.w/s.size_mm?.h||s.logo_px.w/s.logo_px.h;const size=(key,v)=>{if(!positive(v))return showError(new Error('Logo 尺寸必须大于 0'));edit(p=>{const item=p.schemes.find(x=>x.id===s.id);if(item.lock_aspect!==false)item.size_mm=key==='w'?{w:v,h:v/aspect}:{w:v*aspect,h:v};else item.size_mm={...item.size_mm,[key]:v};});};group.append(fieldsRow(field('实际宽 / mm',fmt(s.size_mm?.w),v=>size('w',v),{min:.01}),field('实际高 / mm',fmt(s.size_mm?.h),v=>size('h',v),{min:.01})));const lock=el('label','object-row'),lockCheck=el('input');lockCheck.type='checkbox';lockCheck.checked=s.lock_aspect!==false;lockCheck.onchange=()=>edit(p=>{p.schemes.find(x=>x.id===s.id).lock_aspect=lockCheck.checked;});lock.append(lockCheck,el('span','','锁定原始比例'));group.append(lock);group.append(fieldsRow(field('距区域左 / mm',fmt(s.offset_mm?.left),v=>{if(Number.isFinite(v))edit(p=>{p.schemes.find(x=>x.id===s.id).offset_mm.left=v;});}),field('距区域底 / mm',fmt(s.offset_mm?.bottom),v=>{if(Number.isFinite(v))edit(p=>{p.schemes.find(x=>x.id===s.id).offset_mm.bottom=v;});})));const colors=el('div','color-modes');for(const [mode,label]of [['original','原色'],['black','黑色'],['white','白色'],['gray','深灰']])colors.append(button(label,()=>edit(p=>{p.schemes.find(x=>x.id===s.id).color=mode;}),`${(s.color||'original')===mode?'active':''}`));group.append(el('p','field-label','显示颜色'),colors);const actions=el('div','asset-actions');actions.append(button('水平居中',()=>edit(p=>{const item=p.schemes.find(x=>x.id===s.id),f=p.frames.find(f=>f.id===item.frame_id);item.offset_mm.left=(f.w/ppm-item.size_mm.w)/2;})),button('垂直居中',()=>edit(p=>{const item=p.schemes.find(x=>x.id===s.id),f=p.frames.find(f=>f.id===item.frame_id);item.offset_mm.bottom=(f.h/ppm-item.size_mm.h)/2;})));group.append(actions);root.append(group);
 }else if(selection){const r=editor.getRect(p,selection);if(r){const group=section(selection.kind==='product'?'产品尺寸框':selection.kind==='crop'?'裁剪范围 · 独立于校准':'印标区域');if(selection.kind==='frame')group.append(field('区域名称',r.name||'',v=>edit(p=>{p.frames.find(f=>f.id===selection.id).name=v;}),{type:'text'}));const change=(key,value)=>{if(!Number.isFinite(value)||(['w','h'].includes(key)&&value<=0))return;edit(p=>{editor.getRect(p,selection)[key]=value;});};group.append(fieldsRow(field('X / px',fmt(r.x),v=>change('x',v)),field('Y / px',fmt(r.y),v=>change('y',v))),fieldsRow(field('宽 / px',fmt(r.w),v=>change('w',v),{min:1}),field('高 / px',fmt(r.h),v=>change('h',v),{min:1})));if(selection.kind==='frame'){group.append(button('删除印标区域',()=>{const count=p.schemes.filter(s=>s.frame_id===selection.id).length;if(count&&!confirm('删除此印标区域会移除当前 Logo 位置。继续？'))return;edit(p=>{p.frames=p.frames.filter(f=>f.id!==selection.id);p.schemes=p.schemes.filter(s=>s.frame_id!==selection.id);state.schemeId=p.schemes[0]?.id||null;state.selection=null;});},'small-button danger'));}if(selection.kind==='crop')group.append(button('移除裁剪',()=>edit(p=>{p.crop=null;state.selection=null;}),'small-button'));root.append(group);}}
 if(!p.frames.length){const s=section('印标区域');s.append(button('＋ 框出印标区域',()=>setTool('frame'),'full'));root.append(s);}if(!p.asset&&(p.inputs.logo_svg||p.inputs.logo_source))root.append(el('div','notice','历史素材需要重新分析。打开任务不会改写原始数据。'));if(ppm&&p.schemes.some(s=>{const f=p.frames.find(f=>f.id===s.frame_id);if(!f||!s.size_mm||!s.offset_mm)return true;const r=projectRect(s,f,ppm);return ['x','y','w','h'].some(k=>Math.abs(r[k]-s.logo_px?.[k])>.1);}))root.append(el('div','notice','历史像素与毫米记录不一致。首次编辑时将按毫米尺寸重新定位，请检查。'));}
const actionLabels={
 'create-task':'新建任务','upload-bag':'导入产品图','upload-logo':'导入 Logo','choose-logo':'确认 Logo','calibrate':'标定产品尺寸','place-logo':'放置 Logo','export-customer':'生成客户确认图',
};
function currentActionLabel(action){if(action==='choose-logo'&&!state.project?.asset)return '分析 Logo';if(action==='place-logo'&&!state.project?.frames?.length)return '框出印标区域';return actionLabels[action];}
function primaryAction(){const action=nextPrimaryAction(state.project);if(action==='create-task')return nameDialog();if(action==='upload-bag')return upload('bag');if(action==='upload-logo')return upload('logo');if(action==='choose-logo')return state.project.asset?reviewAsset():analyze();if(action==='calibrate')return setTool('product');if(action==='place-logo')return state.project.frames.length?addScheme():setTool('frame');if(action==='export-customer')return exportDialog();}
function renderTabs(){const assets=state.leftTab==='assets';$('assets-tab').classList.toggle('active',assets);$('assets-tab').setAttribute('aria-selected',String(assets));$('versions-tab').classList.toggle('active',!assets);$('versions-tab').setAttribute('aria-selected',String(!assets));$('assets-view').hidden=!assets;$('versions-view').hidden=assets;const root=$('versions-view');root.replaceChildren();if(!state.project)root.append(el('p','empty-note','打开任务后查看版本记录。'));else root.append(el('p','empty-note',state.project.version_count?'选择一个版本查看客户确认图。':'生成客户确认图后，版本会保存在这里。'));}
function renderPrimaryAction(){const action=nextPrimaryAction(state.project),label=currentActionLabel(action),disabled=state.busy||Boolean(state.queue?.error);const top=$('primary-top-action');top.textContent=label;top.disabled=disabled;const root=$('primary-action-area');root.replaceChildren();root.append(button(label,safe(primaryAction),'primary'));root.firstChild.disabled=disabled;}
function render(){const p=state.project;$('project-title').textContent=p?.name||'选择一个任务，开始制作';if(!state.dirty&&!state.queue?.error)$('save-state').textContent=p?`已保存 · 修订 ${p.revision||0}`:'本地工作空间';$('clone-project').disabled=!p||state.busy;$('settings-button').disabled=state.busy;$('undo-button').disabled=!state.history?.canUndo||state.busy;$('redo-button').disabled=!state.history?.canRedo||state.busy;$('canvas-empty').hidden=Boolean(p?.inputs?.bag_image);$('empty-create').textContent=p?'＋ 导入产品图':'＋ 新建任务';renderProjects();renderAssets();renderTabs();renderProperties();renderPrimaryAction();editor.render();}
function setTool(tool){editor.tool=tool;editor.clean=false;for(const t of ['select','product','frame','crop'])$('tool-'+t).classList.toggle('active',t===tool);$('preview-button').classList.remove('active');editor.svg.style.cursor=tool==='select'?'':'crosshair';editor.render();}
function historyMove(redo){if(state.busy||!state.history||!(redo?state.history.canRedo:state.history.canUndo))return;const revision=state.project.revision;state.project=redo?state.history.redo():state.history.undo();state.project.revision=revision;state.schemeId=state.project.schemes.some(s=>s.id===state.schemeId)?state.schemeId:state.project.schemes[0]?.id||null;state.selection=state.schemeId?{kind:'scheme',id:state.schemeId}:null;state.exported=null;state.dirty=true;state.queue.schedule(state.project);render();}
function exportDialog(){if(!exportReady(state.project))return;const root=dialog('导出生产文件');root.append(el('p','muted','先保存当前排版，再按这一修订导出。PNG 是不含框线和标注的干净效果图。'));const checks=[];for(const s of state.project.schemes){const row=el('label','object-row'),check=el('input');check.type='checkbox';check.checked=true;row.append(check,el('span','',s.name||'方案'));root.append(row);checks.push({check,id:s.id});}const formatRow=el('div','export-row');formatRow.append(el('span','','✓ 干净 PNG　'));const formats=[];for(const value of ['svg','pdf']){const label=el('label'),check=el('input');check.type='checkbox';label.append(check,document.createTextNode(` ${value.toUpperCase()} 规格与位置图　`));formatRow.append(label);formats.push({check,value});}root.append(formatRow);const results=el('div','export-files'),footer=el('div','dialog-footer'),start=button('保存并导出',async()=>{const ids=checks.filter(c=>c.check.checked).map(c=>c.id);if(!ids.length){dialogError(root,new Error('至少选择一个方案'));return;}start.disabled=true;try{await run('正在导出文件…',async()=>{await state.queue.flush();const p=state.project,result=await api(projectURL(p.name)+'/export',{method:'POST',body:{scheme_ids:ids,formats:['png',...formats.filter(f=>f.check.checked).map(f=>f.value)],comparison:false,revision:p.revision}});state.exported=result;results.replaceChildren();results.append(el('p','',`修订 ${result.revision} · 已生成 ${result.files.length} 个文件${result.skipped?.length?` · 跳过 ${result.skipped.length} 项`:''}`));for(const path of result.files){const a=el('a','',path);a.href=fileURL(p,path);a.target='_blank';a.rel='noopener';a.download=path.split('/').pop();results.append(a);}for(const warning of result.warnings||[])results.append(el('div','notice',warning.message||String(warning)));if(result.skipped?.length)results.append(el('div','notice',result.skipped.map(s=>s.message||s.reason||JSON.stringify(s)).join('；')));results.append(button('打开输出文件夹',safe(()=>api(projectURL(p.name)+'/open-output',{method:'POST',body:{}}))));});}catch(error){dialogError(root,error);}finally{start.disabled=false;}},'primary');footer.append(button('关闭',closeDialog),start);root.append(results,footer);}
function settingsDialog(){const root=dialog('本地导出设置');root.append(el('p','muted','PNG / PDF 与矢量分析使用本机 Inkscape。填写已安装的可执行文件路径。'));const path=field('Inkscape 程序路径',state.health?.engine_path||'',()=>{},{type:'text'});root.append(path,el('p','muted',`项目目录：${state.health?.data_dir||'加载中'}`));const footer=el('div','dialog-footer');footer.append(button('取消',closeDialog),button('保存设置',async()=>{try{state.health=await api('/api/engine',{method:'POST',body:{path:path.querySelector('input').value.trim()}});await checkHealth();closeDialog();}catch(error){dialogError(root,error);}},'primary'));root.append(footer);}
async function checkHealth(){state.health=await api('/api/health');$('engine-status').textContent=state.health.available?'Inkscape 已就绪':'Inkscape 未就绪 · 点击设置';}
$('new-project').onclick=()=>nameDialog();$('empty-create').onclick=safe(primaryAction);$('clone-project').onclick=()=>nameDialog(true);$('refresh-projects').onclick=safe(refresh);$('project-search').oninput=renderProjects;$('settings-button').onclick=settingsDialog;$('primary-top-action').onclick=safe(primaryAction);$('assets-tab').onclick=()=>{state.leftTab='assets';render();};$('versions-tab').onclick=()=>{state.leftTab='versions';render();};$('undo-button').onclick=()=>historyMove(false);$('redo-button').onclick=()=>historyMove(true);$('fit-button').onclick=()=>editor.fit();$('zoom-in').onclick=()=>editor.zoom(1.2);$('zoom-out').onclick=()=>editor.zoom(1/1.2);$('preview-button').onclick=()=>{editor.clean=!editor.clean;$('preview-button').classList.toggle('active',editor.clean);editor.render();};for(const tool of ['select','product','frame','crop'])$('tool-'+tool).onclick=()=>setTool(tool);$('dismiss-error').onclick=()=>$('error-banner').hidden=true;$('retry-button').onclick=safe(async()=>{await state.queue.retry();$('error-banner').hidden=true;render();});$('reopen-button').onclick=safe(async()=>{if(!confirm('重新打开会丢弃当前未保存的修改，读取磁盘上的最新修订。继续？'))return;await run('正在读取最新修订…',async()=>adopt(await api(projectURL(state.project.name))));});
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||$('dialog').open||state.busy)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();historyMove(e.shiftKey);}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();historyMove(true);}else if(e.key.toLowerCase()==='v')setTool('select');});window.addEventListener('beforeunload',e=>{if(state.dirty||state.queue?.pending||state.queue?.running){e.preventDefault();e.returnValue='';}});
render();Promise.allSettled([refresh(),checkHealth()]).then(results=>{for(const r of results)if(r.status==='rejected')showError(r.reason);});
