import {copy,positive,validRect,ppmOf,newScheme,projectRect,reproject,History} from './geometry.mjs?v=placement-editor';
import {SaveQueue,api,projectURL,fileURL,runExclusive,customerExport,productionExport,listVersions,restoreVersion,deleteProject,deleteVersion} from './persistence.mjs?v=version-workbench-task-actions';
import {Editor} from './editor.mjs?v=placement-editor-crop-free';
import {$,el,button,field,section,dialog,dialogError,closeDialog,errorBanner} from './ui.mjs';
import {logoPickerDialog} from './assets.mjs?v=candidate-picker';
import {activeScheme,canCustomerExport,nextPrimaryAction,selectedProjectName,suggestedFilename,taskActionState} from './state.mjs?v=task-actions';
import {formatVersionLabel,versionActionState,formatVersionTime,renderVersionList} from './versions.mjs?v=version-workbench';

const state={project:null,projects:[],selection:null,schemeId:null,busy:false,history:null,queue:null,dirty:false,exported:null,health:null,leftTab:'assets',versions:[],versionsLoaded:false,selectedVersionId:null,productionVersionId:null,productionFiles:[]};
const editor=new Editor($('editor'),{getState:()=>state,onSelect:selection=>{state.selection=selection;if(selection?.kind==='scheme')state.schemeId=selection.id;render();},onChange:(p,commit,error)=>{if(error){showError(error);return;}state.project=p;if(commit)changed();else{state.exported=null;editor.render();renderProperties();}},onDraw:(kind,r)=>{if(kind==='product'&&validRect(state.project?.calibration?.product_frame)){state.selection={kind:'product',id:'product'};setTool('select');render();return;}if(kind==='frame'&&state.project?.frames?.length){state.selection={kind:'frame',id:state.project.frames[0].id};setTool('select');render();return;}edit(p=>{if(kind==='product'){p.calibration={...p.calibration,product_frame:r,locked:false};state.selection={kind:'product',id:'product'};}else{const f={...r,id:crypto.randomUUID(),name:'印标区域',locked:false};p.frames=[f];state.selection={kind:'frame',id:f.id};}});setTool('select');},onZoom:scale=>$('zoom-label').textContent=`${Math.round(scale*100)}%`});
editor.onImageLoad=render;
function showError(error){errorBanner(error);$('retry-button').hidden=!state.queue?.error||error.code==='REVISION_CONFLICT';$('reopen-button').hidden=error.code!=='REVISION_CONFLICT';if(state.queue?.error)$('save-state').textContent=error.code==='REVISION_CONFLICT'?'版本冲突 · 已暂停保存':'保存失败 · 修改尚未写入';}
async function run(label,work){try{return await runExclusive(state,work,busy=>{if(busy)$('busy-label').textContent=label;$('busy-overlay').hidden=!busy;render();});}catch(error){showError(error);throw error;}}
function safe(work){return (...args)=>Promise.resolve().then(()=>work(...args)).catch(showError);}
async function refresh(){state.projects=await api('/api/projects');renderProjects();}
function selectedVersion(){return state.versions.find(version=>version.version_id===state.selectedVersionId)||null;}
async function openVersions(){if(!state.project)return;await run('正在读取版本记录…',async()=>{await state.queue?.flush();state.leftTab='versions';state.versionsLoaded=false;render();state.versions=await listVersions(state.project.name);state.versionsLoaded=true;state.selectedVersionId=state.versions[0]?.version_id||null;render();});}
async function exportCustomer(){let exported=false;await run('正在生成客户确认图…',async()=>{await state.queue.flush();const result=await customerExport(state.project,suggestedFilename(state.project));if(result.cancelled)return;exported=true;adopt(await api(projectURL(state.project.name)));await api(projectURL(state.project.name)+'/open-output',{method:'POST'});await refresh();});if(exported)await openVersions();}
async function exportProduction(){const version=selectedVersion();if(!version)return;await run('正在导出生产文件…',async()=>{const result=await productionExport(state.project,version.version_id);state.productionVersionId=version.version_id;state.productionFiles=result.files||[];await api(projectURL(state.project.name)+'/open-output',{method:'POST'});render();});}
async function restoreSelectedVersion(){const version=selectedVersion();if(!version)return;if(!confirm(`从${formatVersionLabel(version)}继续编辑？当前草稿会被此版本替换。`))return;await run('正在恢复版本…',async()=>{await state.queue.flush();adopt(await restoreVersion(state.project,version.version_id));await refresh();});}
async function deleteSelectedVersion(){const version=selectedVersion();if(!version||!versionActionState(version).canDelete)return;if(!confirm(`删除${formatVersionLabel(version)}？只删除软件内部存档，已发送的客户确认图不会受影响。`))return;await run('正在删除版本…',async()=>{await state.queue?.flush();await deleteVersion(state.project.name,version.version_id);state.versions=await listVersions(state.project.name);state.selectedVersionId=state.versions[0]?.version_id||null;state.versionsLoaded=true;await refresh();render();});}
function clearActiveProject(){Object.assign(state,{project:null,selection:null,schemeId:null,history:null,queue:null,dirty:false,exported:null,leftTab:'assets',versions:[],versionsLoaded:false,selectedVersionId:null,productionVersionId:null,productionFiles:[]});}
async function deleteSelectedProject(){const current=state.project;if(!current)return;const name=current.name;if(!confirm(`删除任务“${name}”？\n\n产品图、Logo、版本存档及本机导出文件将永久删除，无法恢复。`))return;await run('正在删除任务…',async()=>{await state.queue?.flush();await deleteProject(name);clearActiveProject();await refresh();render();});}
function adopt(p){state.project=copy(p);state.project.frames??=[];state.project.schemes??=[];state.project.inputs??={};state.history=new History(p);state.schemeId=activeScheme(p)?.id||p.schemes?.[0]?.id||null;state.selection=state.schemeId?{kind:'scheme',id:state.schemeId}:validRect(p.calibration?.product_frame)?{kind:'product',id:'product'}:null;state.dirty=false;state.exported=null;state.leftTab='assets';state.versions=[];state.versionsLoaded=false;state.selectedVersionId=null;state.productionVersionId=null;state.productionFiles=[];state.queue=new SaveQueue(data=>api(projectURL(data.name),{method:'PUT',body:data}),saved=>{state.project.revision=saved.revision;state.project.updated_at=saved.updated_at;state.project.schema_version=saved.schema_version;state.dirty=Boolean(state.queue.pending);$('save-state').textContent=state.dirty?'正在保存…':`已保存 · 修订 ${saved.revision}`;},showError);$('error-banner').hidden=true;render();if(state.project.schemes.length>1)legacySchemeDialog();}
async function openProject(name){await run('正在打开项目…',async()=>{await state.queue?.flush();adopt(await api(projectURL(name)));});}
function changed(){state.project=reproject(state.project);state.project.schema_version=3;state.history.commit(state.project);state.exported=null;state.dirty=true;state.queue.schedule(state.project);$('save-state').textContent='等待保存…';render();}
function edit(mutator){if(state.busy||!state.project)return;mutator(state.project);changed();}
async function mutation(path,body){await state.queue?.flush();const project=await api(projectURL(state.project.name)+path,{method:'POST',body});adopt(project);await refresh();return project;}
function nameDialog(clone=false){if(clone&&!state.project)return;const root=dialog(clone?'复制为新项目':'新建项目'),name=field('项目名称',clone?`${state.project.name} 副本`:'',()=>{},{type:'text'});root.append(name,el('p','muted','每个项目独立保存产品、素材、尺寸与排版方案。'));const footer=el('div','dialog-footer'),submit=button(clone?'创建副本':'创建项目',async()=>{const value=name.querySelector('input').value.trim();if(!value){dialogError(root,new Error('请输入项目名称'));return;}submit.disabled=true;try{await run('正在创建项目…',async()=>{await state.queue?.flush();const p=await api(clone?projectURL(state.project.name)+'/clone':'/api/projects',{method:'POST',body:{name:value}});adopt(p);await refresh();closeDialog();});}catch(error){dialogError(root,error);}finally{submit.disabled=false;}},'primary');footer.append(button('取消',closeDialog),submit);root.append(footer);name.querySelector('input').focus();name.querySelector('input').onkeydown=e=>{if(e.key==='Enter')submit.click();};}
function legacySchemeDialog(){const project=state.project;if(!project||project.schemes.length<2)return;let selected=project.schemes[0].id;const root=dialog('选择一个 Logo 继续编辑',{canClose:()=>false});root.append(el('p','muted','此任务来自旧版本，包含多个 Logo 放置。请选择一个保留为当前草稿。'));for(const [index,scheme]of project.schemes.entries()){const row=el('label','object-row'),radio=el('input');radio.type='radio';radio.name='legacy-scheme';radio.value=scheme.id;radio.checked=scheme.id===selected;radio.onchange=()=>{selected=scheme.id;};row.append(radio,el('span','',`Logo ${index+1}`));root.append(row);}const footer=el('div','dialog-footer');footer.append(button('继续编辑',()=>{const scheme=copy(state.project.schemes.find(item=>item.id===selected));edit(project=>{project.schemes=[scheme];state.schemeId=scheme.id;state.selection={kind:'scheme',id:scheme.id};});closeDialog();},'primary'));root.append(footer);}
const statusLabel={editing:'编辑中',waiting_feedback:'等待反馈',completed:'已完成'};
function formatUpdatedAt(value){if(!value)return '刚刚创建';const date=new Date(value);return Number.isNaN(date.getTime())?'刚刚更新':date.toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});}
function renderProjects(){const select=$('project-select');select.replaceChildren();const placeholder=el('option','','选择任务');placeholder.value='';placeholder.disabled=true;placeholder.selected=!state.project;select.append(placeholder);for(const p of state.projects){const option=el('option','',`${p.name} · ${statusLabel[p.status]||'编辑中'} · ${p.version_count||0} 个版本`);option.value=p.name;option.selected=p.name===state.project?.name;select.append(option);}select.disabled=state.busy||!state.projects.length;}
function upload(kind){if(!state.project){nameDialog();return;}const input=el('input');input.type='file';input.accept=kind==='bag'?'.png,.jpg,.jpeg,.webp':'.svg,.pdf,.ai,.png,.jpg,.jpeg,.webp';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;if(kind==='bag'&&state.project.inputs.bag_image&&!confirm('替换产品图片会清空尺寸校准、参考框和排版方案。是否继续？'))return;try{await run('正在导入素材…',async()=>{const data=new FormData();data.append('file',file);await mutation(`/upload/${kind}`,data);});}catch{}};input.click();}
async function analyze(){await run('正在分析与清理 Logo…',()=>mutation('/convert',{}));reviewAsset();}
function reviewAsset(){logoPickerDialog(state.project,ids=>run('正在应用 Logo…',()=>mutation('/asset/select',{candidate_ids:ids})));}
function renderAssets(){const root=$('assets-panel');root.replaceChildren();const p=state.project;if(!p){root.append(el('p','empty-note','选择任务后，可导入产品图和 Logo。'));return;}const status=el('label','field task-status','任务状态'),select=el('select');for(const [value,label]of Object.entries(statusLabel)){const option=el('option','',label);option.value=value;option.selected=(p.status||'editing')===value;select.append(option);}select.onchange=()=>edit(project=>{project.status=select.value;});status.append(select);root.append(status);const hasLogoSource=Boolean(p.inputs.logo_source||p.inputs.logo_svg);for(const [kind,title,path,help]of [['bag','产品图',p.inputs.bag_image,'JPG / PNG / WebP'],['logo','Logo',p.inputs.logo_preview||p.asset?.source_preview,'SVG / PDF / AI / 位图']]){const isLogo=kind==='logo',isImportedLogo=isLogo&&hasLogoSource,card=el('div',`asset-card${isImportedLogo?' logo-imported':''}`),thumb=el('div','asset-thumb');if(path){const img=el('img');img.src=fileURL(p,path);img.alt=title;thumb.append(img);}else thumb.append(el('span','muted',kind==='bag'?'＋ 添加产品图':isImportedLogo?'◇ Logo 文件':'◇ 导入 Logo'));card.append(thumb);if(isImportedLogo)card.append(el('span','asset-status',p.asset?'Logo 已准备':'Logo 已导入'));card.append(el('h3','',isImportedLogo?(p.asset?'已选定内容':'等待分析'):title));const detail=el('div','muted',isImportedLogo?p.inputs.logo_source.split('/').pop():help);if(isImportedLogo)detail.classList.add('asset-filename');card.append(detail);const actions=el('div','asset-actions');actions.append(button(path||isImportedLogo?'替换文件':'导入文件',()=>upload(kind),'quiet-action'));if(isLogo&&p.asset){actions.append(button('选择内容',reviewAsset),button('重新分析',safe(analyze),'quiet-action'));}card.append(actions);root.append(card);}}
function selectedFrame(){const p=state.project;if(!p)return null;if(state.selection?.kind==='frame')return p.frames.find(f=>f.id===state.selection.id);const s=p.schemes.find(s=>s.id===state.schemeId);return p.frames.find(f=>f.id===s?.frame_id)||p.frames[0];}
function ensurePlacement(project,frame=project.frames?.[0]){if(project.schemes?.length||!project.asset||!frame||!ppmOf(project))return null;const scheme=newScheme(project,frame.id);if(!scheme)return null;project.schemes=[scheme];state.schemeId=scheme.id;return scheme;}
function addScheme(){const p=state.project,f=selectedFrame();if(!f)return;if(p.schemes.length){state.schemeId=p.schemes[0].id;state.selection={kind:'scheme',id:state.schemeId};render();return;}edit(project=>{const scheme=ensurePlacement(project,f);if(scheme)state.selection={kind:'scheme',id:scheme.id};});}
const fmt=n=>Number.isFinite(n)?Number(n.toFixed(2)):'';
function fieldsRow(...fields){const row=el('div','field-row');row.append(...fields);return row;}
const colorLabel={original:'原色',black:'黑色',white:'白色',gray:'深灰'};
function renderVersionProperties(root){const version=selectedVersion();$('selection-kind').textContent='版本';if(!version)return;const details=section(formatVersionLabel(version));details.append(el('p','muted',formatVersionTime(version.created_at)),el('p','muted',`Logo 尺寸：${fmt(version.logo_width_mm)} × ${fmt(version.logo_height_mm)} mm`),el('p','muted',`显示颜色：${colorLabel[version.color]||'原色'}`));root.append(details);const production=section('生产文件');production.append(el('p','muted','按此存档版本导出 Logo 尺寸稿（PDF、SVG）和印刷定位图。'));const exportButton=button('导出生产文件',safe(exportProduction),'full');exportButton.disabled=state.busy;production.append(exportButton);if(state.productionVersionId===version.version_id&&state.productionFiles.length){const files=el('div','export-files');for(const path of state.productionFiles){const link=el('a','',path.split('/').pop());link.href=fileURL(state.project,path);link.target='_blank';files.append(link);}production.append(files);}root.append(production);const actions=section('版本操作');actions.append(button('从此版本继续编辑',safe(restoreSelectedVersion),'full'));if(versionActionState(version).canDelete)actions.append(button('删除此版本',safe(deleteSelectedVersion),'small-button danger'));else actions.append(el('p','muted','旧版导出仅可恢复，不能删除。'));root.append(actions);}
function geometryLocked(project,selection){return selection?.kind==='product'?Boolean(project?.calibration?.locked):selection?.kind==='frame'?Boolean(project?.frames?.find(frame=>frame.id===selection.id)?.locked):false;}
function toggleGeometryLock(selection){if(!selection)return;edit(project=>{if(selection.kind==='product')project.calibration={...project.calibration,locked:!project.calibration.locked};else if(selection.kind==='frame'){const frame=project.frames.find(item=>item.id===selection.id);if(frame)frame.locked=!frame.locked;}});}
function geometryHeading(group,selection,locked){const heading=group.querySelector('h3'),toggle=button(locked?'🔒':'🔓',()=>toggleGeometryLock(selection),'lock-toggle');heading.classList.add('section-heading');toggle.title=locked?'解除锁定':'锁定';toggle.setAttribute('aria-label',locked?'解除锁定':'锁定');heading.append(toggle);}
function activateGeometryTool(kind){const project=state.project;if(!project)return;const selection=kind==='product'&&validRect(project.calibration?.product_frame)?{kind:'product',id:'product'}:kind==='frame'&&project.frames?.length?{kind:'frame',id:project.frames[0].id}:null;if(selection){state.selection=selection;setTool('select');render();return;}setTool(kind);}
function reuseProductFrame(){const product=state.project?.calibration?.product_frame;if(!validRect(product)||state.project?.frames?.length)return;edit(project=>{const frame={...product,id:crypto.randomUUID(),name:'印标区域',locked:false};project.frames=[frame];state.selection={kind:'frame',id:frame.id};});}
function renderProperties(){const root=$('properties'),p=state.project;root.replaceChildren();if(!p){$('selection-kind').textContent='项目';root.append(el('p','empty-note','从顶部选择或新建任务。所有修改自动保存在本机。'));return;}if(state.leftTab==='versions'){renderVersionProperties(root);return;}$('selection-kind').textContent=({product:'产品框',frame:'印标区域',scheme:'Logo'})[state.selection?.kind]||'项目';const calibration=section('产品校准');calibration.append(field('产品实际宽度 / mm',p.calibration?.width_mm||'',v=>{if(!positive(v)){showError(new Error('产品宽度必须大于 0'));return;}edit(project=>{project.calibration={...project.calibration,width_mm:v};});},{min:.01}));const ppm=ppmOf(p);calibration.append(el('p','muted',ppm?`比例 ${fmt(ppm)} px/mm · 高度 ${fmt(p.calibration.product_frame.h/ppm)} mm`:'请在图片上绘制产品尺寸框，再输入真实宽度。'));if(!validRect(p.calibration?.product_frame))calibration.append(button('绘制产品尺寸框',()=>activateGeometryTool('product'),'full'));root.append(calibration);const selection=state.selection;
 if(selection?.kind==='scheme'){const s=p.schemes.find(s=>s.id===selection.id);if(!s)return;const group=section('Logo 尺寸与定位');const frameField=el('label','field','印标区域'),select=el('select');for(const f of p.frames){const opt=el('option','',f.name||'印标区域');opt.value=f.id;opt.selected=f.id===s.frame_id;select.append(opt);}select.onchange=()=>edit(project=>{project.schemes.find(x=>x.id===s.id).frame_id=select.value;});frameField.append(select);group.append(frameField);const aspect=p.asset?.width/p.asset?.height||s.size_mm?.w/s.size_mm?.h||s.logo_px.w/s.logo_px.h;const size=(key,v)=>{if(!positive(v))return showError(new Error('Logo 尺寸必须大于 0'));edit(project=>{const item=project.schemes.find(x=>x.id===s.id);if(item.lock_aspect!==false)item.size_mm=key==='w'?{w:v,h:v/aspect}:{w:v*aspect,h:v};else item.size_mm={...item.size_mm,[key]:v};});};group.append(fieldsRow(field('实际宽 / mm',fmt(s.size_mm?.w),v=>size('w',v),{min:.01}),field('实际高 / mm',fmt(s.size_mm?.h),v=>size('h',v),{min:.01})));const lock=el('label','object-row'),lockCheck=el('input');lockCheck.type='checkbox';lockCheck.checked=s.lock_aspect!==false;lockCheck.onchange=()=>edit(project=>{project.schemes.find(x=>x.id===s.id).lock_aspect=lockCheck.checked;});lock.append(lockCheck,el('span','','锁定原始比例'));group.append(lock);group.append(fieldsRow(field('距区域左 / mm',fmt(s.offset_mm?.left),v=>{if(Number.isFinite(v))edit(project=>{project.schemes.find(x=>x.id===s.id).offset_mm.left=v;});}),field('距区域底 / mm',fmt(s.offset_mm?.bottom),v=>{if(Number.isFinite(v))edit(project=>{project.schemes.find(x=>x.id===s.id).offset_mm.bottom=v;});})));const colors=el('div','color-modes');for(const [mode,label]of [['original','原色'],['black','黑色'],['white','白色'],['gray','深灰']])colors.append(button(label,()=>edit(project=>{project.schemes.find(x=>x.id===s.id).color=mode;}),`${(s.color||'original')===mode?'active':''}`));group.append(el('p','field-label','显示颜色'),colors);const actions=el('div','asset-actions');actions.append(button('水平居中',()=>edit(project=>{const item=project.schemes.find(x=>x.id===s.id),frame=project.frames.find(f=>f.id===item.frame_id);item.offset_mm.left=(frame.w/ppm-item.size_mm.w)/2;})),button('垂直居中',()=>edit(project=>{const item=project.schemes.find(x=>x.id===s.id),frame=project.frames.find(f=>f.id===item.frame_id);item.offset_mm.bottom=(frame.h/ppm-item.size_mm.h)/2;})));group.append(actions);root.append(group);
 }else if(selection){const r=editor.getRect(p,selection);if(r){const locked=geometryLocked(p,selection),group=section(selection.kind==='product'?'产品尺寸框':'印标区域');geometryHeading(group,selection,locked);if(selection.kind==='frame')group.append(field('区域名称',r.name||'',v=>edit(project=>{project.frames.find(frame=>frame.id===selection.id).name=v;}),{type:'text'}));const change=(key,value)=>{if(locked||!Number.isFinite(value)||(['w','h'].includes(key)&&value<=0))return;edit(project=>{editor.getRect(project,selection)[key]=value;});};const coordinateField=(label,value,key,options)=>{const node=field(label,value,v=>change(key,v),options);node.querySelector('input').disabled=locked;return node;};group.append(fieldsRow(coordinateField('X / px',fmt(r.x),'x'),coordinateField('Y / px',fmt(r.y),'y')),fieldsRow(coordinateField('宽 / px',fmt(r.w),'w',{min:1}),coordinateField('高 / px',fmt(r.h),'h',{min:1})));if(selection.kind==='frame'){const remove=button('删除印标区域',()=>{const count=p.schemes.filter(s=>s.frame_id===selection.id).length;if(count&&!confirm('删除此印标区域会移除当前 Logo 位置。继续？'))return;edit(project=>{project.frames=project.frames.filter(frame=>frame.id!==selection.id);project.schemes=project.schemes.filter(scheme=>scheme.frame_id!==selection.id);state.schemeId=project.schemes[0]?.id||null;state.selection=null;});},'small-button danger');remove.disabled=locked;remove.title=locked?'解除锁定后可删除':'';group.append(remove);}root.append(group);}}
 if(!p.frames.length){const printArea=section('印标区域'),actions=el('div','split-actions'),reuse=button('复用产品尺寸框',reuseProductFrame,'');reuse.disabled=!validRect(p.calibration?.product_frame);reuse.title=reuse.disabled?'请先完成产品尺寸框':'';actions.append(button('＋ 框出印标区',()=>activateGeometryTool('frame'),''),reuse);printArea.append(actions);root.append(printArea);}}
const actionLabels={
 'create-task':'新建任务','upload-bag':'导入产品图','upload-logo':'导入 Logo','analyze-logo':'分析 Logo','choose-logo':'确认 Logo','calibrate':'标定产品尺寸','lock-product':'锁定产品框','lock-frame':'锁定印标区域','place-logo':'放置 Logo','export-customer':'生成客户确认图',
};
function currentActionLabel(action){if(state.leftTab==='versions')return '返回当前草稿';if(action==='place-logo'&&!state.project?.frames?.length)return '框出印标区域';return actionLabels[action];}
function primaryAction(){if(state.leftTab==='versions'){state.leftTab='assets';render();return;}const action=nextPrimaryAction(state.project);if(action==='create-task')return nameDialog();if(action==='upload-bag')return upload('bag');if(action==='upload-logo')return upload('logo');if(action==='analyze-logo')return analyze();if(action==='choose-logo')return reviewAsset();if(action==='calibrate')return activateGeometryTool('product');if(action==='lock-product')return toggleGeometryLock({kind:'product',id:'product'});if(action==='lock-frame')return toggleGeometryLock({kind:'frame',id:state.project.frames[0]?.id});if(action==='place-logo')return state.project.frames.length?addScheme():activateGeometryTool('frame');if(action==='export-customer'&&canCustomerExport(state.project))return exportCustomer();}
function guideWarning(project){const warning=project?.asset?.warnings?.[0];if(warning){const text=String(warning.message||warning);return `分析提示：${text.slice(0,62)}${text.length>62?'…':''}`;}const ppm=ppmOf(project);if(ppm&&project.schemes?.some(s=>{const frame=project.frames.find(f=>f.id===s.frame_id);if(!frame||!s.size_mm||!s.offset_mm)return true;const rect=projectRect(s,frame,ppm);return ['x','y','w','h'].some(key=>Math.abs(rect[key]-s.logo_px?.[key])>.1);}))return '尺寸记录与当前标定不一致，请在继续编辑前检查。';return '';}
function renderWorkflowGuide(){const project=state.project,action=nextPrimaryAction(project);let title=currentActionLabel(action),detail=({'create-task':'新建任务后，依次导入产品图与客户 Logo。','upload-bag':'先导入产品图，作为本次效果图的底图。','upload-logo':'产品图已准备，接着导入客户提供的 Logo 文件。','analyze-logo':'已导入 Logo；分析可筛除背景、尺寸标注等无关内容。','choose-logo':'从分析结果中选取要保留的 Logo 内容。','calibrate':'在画布中框出产品实际范围，再输入实物宽度。','lock-product':'产品尺寸已确认；锁定后再进入下一步。','lock-frame':'印标区域已确认；锁定后再放置 Logo。','place-logo':'框出印标区域后，拖动 Logo 调整位置和尺寸。','export-customer':'确认 Logo 尺寸与位置后，生成一张客户确认图。'})[action]||'';if(action==='analyze-logo'&&project?.inputs?.logo_source){const name=project.inputs.logo_source.split('/').pop();detail=`已导入 ${name}；分析可筛除背景、尺寸标注等无关内容。`;}if(state.leftTab==='versions'){title='版本记录';detail='正在查看已存档版本，可从任一版本继续编辑。';}const warning=guideWarning(project);if(warning)detail=warning;$('workflow-title').textContent=title;$('workflow-detail').textContent=detail;const next=$('workflow-action');next.textContent=currentActionLabel(action);next.disabled=state.busy||Boolean(state.queue?.error);next.hidden=false;}
function renderTabs(){const assets=state.leftTab==='assets';$('assets-tab').classList.toggle('active',assets);$('assets-tab').setAttribute('aria-selected',String(assets));$('versions-tab').classList.toggle('active',!assets);$('versions-tab').setAttribute('aria-selected',String(!assets));$('assets-view').hidden=!assets;$('versions-view').hidden=assets;if(assets)return;const root=$('versions-view');root.replaceChildren();if(!state.project)root.append(el('p','empty-note','打开任务后查看版本记录。'));else if(!state.versionsLoaded)root.append(el('p','empty-note','正在读取版本记录…'));else renderVersionList(root,state.versions,state.selectedVersionId,id=>{state.selectedVersionId=id;render();});}
function renderVersionPreview(){const viewing=state.leftTab==='versions';const version=viewing?selectedVersion():null;const preview=$('version-preview'),image=$('version-preview-image'),empty=$('version-preview-empty');preview.hidden=!viewing;$('editor').style.visibility=viewing?'hidden':'';document.querySelector('.editor-toolbar').hidden=viewing;document.querySelector('.viewport-controls').hidden=viewing;document.querySelector('.canvas-help').hidden=viewing;$('canvas-empty').hidden=viewing||Boolean(state.project?.inputs?.bag_image);if(!viewing){image.removeAttribute('src');return;}if(version?.preview_path){image.src=fileURL(state.project,version.preview_path);image.hidden=false;empty.hidden=true;return;}image.removeAttribute('src');image.hidden=true;empty.hidden=false;empty.textContent=state.versionsLoaded?(state.versions.length?'此版本没有可预览的确认图。':'尚未生成确认图'):'正在读取版本记录…';}
function renderPrimaryAction(){const action=nextPrimaryAction(state.project),label=currentActionLabel(action),disabled=state.busy||Boolean(state.queue?.error);const top=$('primary-top-action');top.textContent=label;top.disabled=disabled;const root=$('primary-action-area');root.replaceChildren();root.append(button(label,safe(primaryAction),'primary'));root.firstChild.disabled=disabled;}
function render(){const p=state.project,actions=taskActionState(p);$('project-title').textContent=p?.name||'选择一个任务，开始制作';if(!state.dirty&&!state.queue?.error)$('save-state').textContent=p?`已保存 · 修订 ${p.revision||0}`:'本地工作空间';$('clone-project').disabled=!actions.canClone||state.busy;$('delete-project').disabled=!actions.canDelete||state.busy;$('settings-button').disabled=state.busy;$('undo-button').disabled=!state.history?.canUndo||state.busy;$('redo-button').disabled=!state.history?.canRedo||state.busy;$('empty-create').textContent=p?'＋ 导入产品图':'＋ 新建任务';renderProjects();renderAssets();renderTabs();renderProperties();renderVersionPreview();renderWorkflowGuide();renderPrimaryAction();editor.render();}
function setTool(tool){editor.tool=tool;editor.clean=false;for(const t of ['select','product','frame'])$('tool-'+t).classList.toggle('active',t===tool);$('preview-button').classList.remove('active');editor.svg.style.cursor=tool==='select'?'':'crosshair';editor.render();}
function historyMove(redo){if(state.busy||!state.history||!(redo?state.history.canRedo:state.history.canUndo))return;const revision=state.project.revision;state.project=redo?state.history.redo():state.history.undo();state.project.revision=revision;state.schemeId=state.project.schemes.some(s=>s.id===state.schemeId)?state.schemeId:state.project.schemes[0]?.id||null;state.selection=state.schemeId?{kind:'scheme',id:state.schemeId}:null;state.exported=null;state.dirty=true;state.queue.schedule(state.project);render();}
function settingsDialog(){const root=dialog('本地导出设置');root.append(el('p','muted','PNG / PDF 与矢量分析使用本机 Inkscape。填写已安装的可执行文件路径。'));const path=field('Inkscape 程序路径',state.health?.engine_path||'',()=>{},{type:'text'});root.append(path,el('p','muted',`项目目录：${state.health?.data_dir||'加载中'}`));const footer=el('div','dialog-footer');footer.append(button('取消',closeDialog),button('保存设置',async()=>{try{state.health=await api('/api/engine',{method:'POST',body:{path:path.querySelector('input').value.trim()}});await checkHealth();closeDialog();}catch(error){dialogError(root,error);}},'primary'));root.append(footer);}
async function checkHealth(){state.health=await api('/api/health');$('engine-status').textContent=state.health.available?'Inkscape 已就绪':'Inkscape 未就绪 · 点击设置';}
$('new-project').onclick=()=>nameDialog();$('project-select').onchange=event=>{const name=selectedProjectName(event);safe(()=>openProject(name))();};$('empty-create').onclick=safe(primaryAction);$('clone-project').onclick=()=>nameDialog(true);$('delete-project').onclick=safe(deleteSelectedProject);$('settings-button').onclick=settingsDialog;$('primary-top-action').onclick=safe(primaryAction);$('workflow-action').onclick=safe(primaryAction);$('assets-tab').onclick=()=>{state.leftTab='assets';render();};$('versions-tab').onclick=safe(openVersions);$('undo-button').onclick=()=>historyMove(false);$('redo-button').onclick=()=>historyMove(true);$('fit-button').onclick=()=>editor.fit();$('zoom-in').onclick=()=>editor.zoom(1.2);$('zoom-out').onclick=()=>editor.zoom(1/1.2);$('preview-button').onclick=()=>{editor.clean=!editor.clean;$('preview-button').classList.toggle('active',editor.clean);editor.render();};$('tool-select').onclick=()=>setTool('select');$('tool-product').onclick=()=>activateGeometryTool('product');$('tool-frame').onclick=()=>activateGeometryTool('frame');$('dismiss-error').onclick=()=>$('error-banner').hidden=true;$('retry-button').onclick=safe(async()=>{await state.queue.retry();$('error-banner').hidden=true;render();});$('reopen-button').onclick=safe(async()=>{if(!confirm('重新打开会丢弃当前未保存的修改，读取磁盘上的最新修订。继续？'))return;await run('正在读取最新修订…',async()=>adopt(await api(projectURL(state.project.name))));});
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||$('dialog').open||state.busy)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();historyMove(e.shiftKey);}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();historyMove(true);}else if(e.key.toLowerCase()==='v')setTool('select');});window.addEventListener('beforeunload',e=>{if(state.dirty||state.queue?.pending||state.queue?.running){e.preventDefault();e.returnValue='';}});
render();Promise.allSettled([refresh(),checkHealth()]).then(results=>{for(const r of results)if(r.status==='rejected')showError(r.reason);});
